modules:
  acqui:
    histsearch:
      histsearcht:
        -
          columnname: order_line
        -
          columnname: status
        -
          columnname: basket
        -
          columnname: basket_creator
        -
          columnname: basket_group
        -
          columnname: invoice_number
        -
          columnname: summary
        -
          columnname: vendor
        -
          columnname: placed_on
        -
          columnname: received_on
        -
          columnname: quantity_received
        -
          columnname: pending_order
        -
          columnname: unit_cost
        -
          columnname: fund

    lateorders:
      late_orders:
        -
          columnname: checkbox
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: order_date
        -
          columnname: estimated_delivery_date
        -
          columnname: vendor
        -
          columnname: information
        -
          columnname: total_cost
        -
          columnname: basket
        -
          columnname: basket_group
        -
          columnname: library
        -
          columnname: fund
        -
          columnname: claims_count
        -
          columnname: claimed_date

  admin:
    currency:
      currencies-table:
        -
          columnname: currency
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: rate
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: symbol
        -
          columnname: iso_code
          is_hidden: 1
        -
          columnname: last_updated
        -
          columnname: active
        -
          columnname: actions

  cataloguing:
    additem:
      itemst:
        # NOTE: These columns are selected from the non-hidden columns that have mappings to MARC
        # subfields in the default MARC21 framework (and can thus be displayed in the item editor).
        -
          columnname: withdrawn
        -
          columnname: itemlost
        -
          columnname: cn_source
        -
          columnname: materials
        -
          columnname: damaged
        -
          columnname: restricted
        -
          columnname: cn_sort
        -
          columnname: notforloan
        -
          columnname: ccode
        -
          columnname: itemnumber
        -
          columnname: homebranch
        -
          columnname: holdingbranch
        -
          columnname: location
        -
          columnname: dateaccessioned
        -
          columnname: booksellerid
        -
          columnname: coded_location_qualifier
        -
          columnname: price
        -
          columnname: enumchron
        -
          columnname: stocknumber
        -
          columnname: stack
        -
          columnname: issues
        -
          columnname: renewals
        -
          columnname: reserves
        -
          columnname: itemcallnumber
        -
          columnname: barcode
        -
          columnname: onloan
        -
          columnname: datelastseen
        -
          columnname: datelastborrowed
        -
          columnname: copynumber
        -
          columnname: uri
        -
          columnname: replacementprice
        -
          columnname: replacementpricedate
        -
          columnname: itemnotes_nonpublic
        -
          columnname: itype
        -
          columnname: itemnotes

  members:
    member:
      memberresultst:
        -
          columnname: checkbox
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: cardnumber
        -
          columnname: name
        -
          columnname: category
        -
          columnname: library
        -
          columnname: expires_on
        -
          columnname: od_checkouts
        -
          columnname: fines
        -
          columnname: circ_notes
        -
          columnname: actions
          cannot_be_toggled: 1
          cannot_be_modified: 1

    moremember:
      issues-table:
        -
          columnname: sort_order
          cannot_be_toggled: 1
          cannot_be_modified: 1
          is_hidden: 1
        -
          columnname: todays_or_previous_checkouts
          cannot_be_toggled: 1
          cannot_be_modified: 1
          is_hidden: 1
        -
          columnname: due_date_unformatted
          cannot_be_toggled: 1
          cannot_be_modified: 1
          is_hidden: 1
        -
          columnname: due_date
        -
          columnname: title
        -
          columnname: item_type
        -
          columnname: location
        -
          columnname: checkout_on
        -
          columnname: checkout_from
        -
          columnname: callno
        -
          columnname: charge
        -
          columnname: price
        -
          columnname: renew
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: checkin
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: export
          cannot_be_toggled: 1
          cannot_be_modified: 1

  reports:
    lostitems:
      lostitems-table:
        -
          columnname: title
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: author
        -
          columnname: lostcode
        -
          columnname: barcode
        -
          columnname: callnumber
        -
          columnname: datelastseen
        -
          columnname: price
        -
          columnname: replacementprice
        -
          columnname: library
        -
          columnname: itemtype
        -
          columnname: current_location
        -
          columnname: location
        -
          columnname: notes

  circ:
    circulation:
      issues-table:
        -
          columnname: sort_order
          cannot_be_toggled: 1
          cannot_be_modified: 1
          is_hidden: 1
        -
          columnname: todays_or_previous_checkouts
          cannot_be_toggled: 1
          cannot_be_modified: 1
          is_hidden: 1
        -
          columnname: due_date_unformatted
          cannot_be_toggled: 1
          cannot_be_modified: 1
          is_hidden: 1
        -
          columnname: due_date
        -
          columnname: title
        -
          columnname: item_type
        -
          columnname: location
        -
          columnname: checkout_on
        -
          columnname: checkout_from
        -
          columnname: callno
        -
          columnname: charge
        -
          columnname: price
        -
          columnname: renew
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: checkin
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: export
          cannot_be_toggled: 1
          cannot_be_modified: 1
